# Generated by Django 3.2 on 2022-09-04 23:20

import applications.food.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to=applications.food.models.user_directory_path)),
                ('detail_food', models.TextField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True, unique_for_date='published')),
                ('published', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.category')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
