# Generated by Django 4.1.1 on 2022-09-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=80)),
                ("img", models.ImageField(upload_to="")),
                ("detail_food", models.TextField(max_length=150)),
                (
                    "slug",
                    models.SlugField(
                        max_length=150, unique=True, unique_for_date="published"
                    ),
                ),
                ("published", models.DateField(auto_now_add=True)),
                ("price", models.FloatField()),
            ],
            options={
                "ordering": ("-name",),
            },
        ),
    ]
