# Generated by Django 3.2.6 on 2022-09-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
